version: "3.8"

services:
  frontend:
    build:
      context: ./noQ-Frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"

    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev:dev"]
